In [1]:
import numpy as np
import pandas as pd
import string
from nltk.corpus import stopwords
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from nltk.stem.lancaster import LancasterStemmer
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

In [3]:
data=pd.read_csv("train.csv",encoding='latin-1')
data.head()

tweet_id airline_sentiment    airline airline_sentiment_gold  \
0  567900433542488064          negative  Southwest                    NaN   
1  569989168903819264          positive  Southwest                    NaN   
2  568089179520954368          positive     United                    NaN   
3  568928195581513728          negative  Southwest                    NaN   
4  568594180014014464          negative     United                    NaN   

            name negativereason_gold  retweet_count  \
0  ColeyGirouard                 NaN              0   
1  WalterFaddoul                 NaN              0   
2      LocalKyle                 NaN              0   
3    amccarthy19                 NaN              0   
4        J_Okayy                 NaN              0   

                                                text tweet_coord  \
0  @SouthwestAir I am scheduled for the morning, ...         NaN   
1  @SouthwestAir seeing your workers time in and ...         NaN   
2  @united Flew ORD to Miami and back and  had gr...         NaN   
3  @SouthwestAir @dultch97 that's horse radish ðŸ...         NaN   
4  @united so our flight into ORD was delayed bec...         NaN   

               tweet_created              tweet_location  \
0  2015-02-17 20:16:29 -0800             Washington D.C.   
1  2015-02-23 14:36:22 -0800  Indianapolis, Indiana; USA   
2  2015-02-18 08:46:29 -0800                    Illinois   
3  2015-02-20 16:20:26 -0800                         NaN   
4  2015-02-19 18:13:11 -0800                         NaN   

                user_timezone  
0      Atlantic Time (Canada)  
1  Central Time (US & Canada)  
2  Central Time (US & Canada)  
3      Atlantic Time (Canada)  
4  Eastern Time (US & Canada)

In [4]:
#print(data.shape)
data.head()
data.airline_sentiment.value_counts()

negative    6851
neutral     2327
positive    1802
Name: airline_sentiment, dtype: int64

In [6]:
data.airline.value_counts()

United            2928
US Airways        2152
American          2078
Southwest         1817
Delta             1639
Virgin America     366
Name: airline, dtype: int64

In [7]:
train_data=data.iloc[:,7]
train_data=np.array(train_data)
labels_data=data.iloc[:,1]
labels_data=np.array(labels_data)

In [13]:
new_data=pd.DataFrame(train_data)
new_data.columns=['text']
new_data.head()

text
0  @SouthwestAir I am scheduled for the morning, ...
1  @SouthwestAir seeing your workers time in and ...
2  @united Flew ORD to Miami and back and  had gr...
3  @SouthwestAir @dultch97 that's horse radish ðŸ...
4  @united so our flight into ORD was delayed bec...

In [6]:
string.digits,string.punctuation

('0123456789', '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~')

In [7]:
Stopwords = ['a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', "aren't", 'as', 'at',
 'be', 'because', 'been', 'before', 'being', 'but', 'by', 
 'can', "can't", 'cannot', 'could', "couldn't", 'did', "didn't", 'do', 'does', "doesn't", "don't", 'down', 'during',
 'for', 'from', 'further', 
 'had', "hadn't", 'has', "hasn't", 'have', "haven't", 'having', 'he', "he'd", "he'll", "he's", 'her', 'here', "here's",
 'hers', 'herself', 'him', 'himself', 'his', 'how', "how's",
 'i', "i'd", "i'll", "i'm", "i've", 'if', 'in', 'into', 'is', "isn't", 'it', "it's", 'its', 'itself',
 "let's", 'me', 'more', 'most', "mustn't", 'my', 'myself', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'ought', 'our', 'ours' 'ourselves', 'out', 'own',
 'same', "shan't", 'she', "she'd", "she'll", "she's", 'should', "shouldn't", 'so', 'some', 'such', 
 'than', 'that',"that's", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', "there's", 'these', 'they', "they'd", 
 "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 
 'was', "wasn't", 'we', "we'd", "we'll", "we're", "we've", 'were', "weren't", 'what', "what's", 'when', "when's", 'where',
 "where's", 'which', 'while', 'who', "who's", 'whom', 'why', "why's",'will', 'with', "won't", 'would', "wouldn't", 
 'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves', ]

In [8]:
porter=PorterStemmer()
new_stem=WordNetLemmatizer()
Stemmer=LancasterStemmer()

# Removing the numeric and unneccessary data and stopwords from the data

In [9]:
def text_preprocess(text):
    text = [char for char in text if char not in string.punctuation]
    text = ''.join(text)
    text = [char for char in text if char not in string.digits]
    text = ''.join(text)
    text = [word for word in text.split() if word.lower() not in  Stopwords]
    return " ".join(text)

In [10]:
trained_data_cleaned=[]
for i in range(len(train_data)):
    trained_data_cleaned.append(text_preprocess(train_data[i]))    

# Stemming the words by using Porter Stemmer

In [11]:
def new_fun(text):
    text=word_tokenize(text)
    text=[porter.stem(w.lower()) for w in text]
    return ' '.join(text)

In [12]:
new_train=[]
for i in range(len(trained_data_cleaned)):
     new_train.append(new_fun(trained_data_cleaned[i]))

In [13]:
labels_data
labels_data=pd.DataFrame(labels_data)
labels_data.columns=['A']
print(labels_data.A.value_counts())
print(len(labels_data))
print(trained_data_cleaned[0])

negative    6851
neutral     2327
positive    1802
Name: A, dtype: int64
10980
SouthwestAir scheduled morning days fact yesnot sure evening flight one Cancelled Flightled


# Making Our class as in form of Numeric Data

In [14]:
def ui(k):
    if k=='negative':
        return 0
    elif k=='neutral':
        return 1
    elif k=='positive':
        return 2
labels_data['A']=labels_data['A'].apply(ui)

In [15]:
labels_data.A.value_counts()

0    6851
1    2327
2    1802
Name: A, dtype: int64

In [16]:
import nltk 
word=[]
document=[]
for i in new_train:
    wrd=nltk.word_tokenize(i)
    word.extend(wrd)
    document.append(wrd)

In [17]:
len(word)

114814

# Splitting the Data into Train and Test

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(new_train,labels_data,test_size=0.25)

In [20]:
len(x_train),len(x_test),len(y_train),len(y_test)

(8235, 2745, 8235, 2745)

In [21]:
import matplotlib.pyplot as plt

# Counting the Word Frequency and inverse of it

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
Vectorizer=TfidfVectorizer(ngram_range=(1,5),max_features=1500)

In [24]:
X_train=Vectorizer.fit_transform(x_train)
X_test=Vectorizer.transform(x_test)

In [25]:
labels_data=np.array(labels_data)
labels_data.ravel()
labels_data.shape

(10980, 1)

In [26]:
print(sorted((Vectorizer.get_feature_names())))

['aa', 'abl', 'abl get', 'absolut', 'absurd', 'accept', 'access', 'accommod', 'account', 'actual', 'ad', 'add', 'addit', 'address', 'admir', 'admir club', 'advis', 'advisori', 'afford', 'afternoon', 'agent', 'ago', 'ahead', 'air', 'aircraft', 'airlin', 'airlin ever', 'airplan', 'airport', 'airway', 'alert', 'allow', 'almost', 'almost hour', 'alreadi', 'also', 'altern', 'although', 'alway', 'amaz', 'american', 'american airlin', 'americanair', 'americanair aa', 'americanair call', 'americanair cancel', 'americanair cancel flight', 'americanair cant', 'americanair dont', 'americanair flight', 'americanair flight cancel', 'americanair flight cancel flightl', 'americanair got', 'americanair guy', 'americanair help', 'americanair hey', 'americanair hour', 'americanair im', 'americanair ive', 'americanair just', 'americanair need', 'americanair no', 'americanair not', 'americanair now', 'americanair ok', 'americanair pleas', 'americanair still', 'americanair thank', 'americanair tri', 'ameri

In [27]:

freq=nltk.FreqDist(word)
print(sorted((freq.most_common(1500))))


[('aa', 207), ('abl', 98), ('absolut', 38), ('absurd', 11), ('accept', 45), ('access', 31), ('accommod', 26), ('accord', 8), ('account', 59), ('acct', 12), ('act', 11), ('action', 10), ('actual', 75), ('ad', 34), ('add', 67), ('addit', 15), ('address', 38), ('admir', 14), ('advanc', 9), ('advantag', 13), ('advis', 15), ('advisori', 17), ('affect', 10), ('afford', 13), ('afternoon', 23), ('age', 12), ('agent', 329), ('ago', 97), ('ah', 10), ('ahead', 14), ('air', 103), ('aircraft', 25), ('airfar', 10), ('airlin', 420), ('airplan', 18), ('airport', 273), ('airway', 72), ('alert', 14), ('alist', 8), ('allianc', 9), ('allow', 67), ('almost', 70), ('alon', 13), ('along', 13), ('alreadi', 136), ('alright', 9), ('also', 95), ('altern', 15), ('although', 12), ('alway', 89), ('amaz', 73), ('america', 15), ('american', 56), ('americanair', 2218), ('americanairlin', 20), ('amount', 11), ('amp', 487), ('angri', 14), ('announc', 40), ('annoy', 13), ('anoth', 213), ('answer', 151), ('anymor', 18), (

In [28]:
  #  a=['prove','proved',"good","excellent","painting","paint"]
   # b=[]
    #print(a)
   # b=[Stemmer.stem(w.lower()) for w in a]
   # c=[new_stem.lemmatize(w.lower()) for w in a]
   # d=[porter.stem(w.lower()) for w  in a]
   # b,c,d

In [29]:
# a='kajkakajkj,kjkdjkjd ssjshjshjshjhsy shshs sbsgsgshhgs'
 #   word_tokenize(a)
  #  c=word_tokenize(train_data[0])
   # print(word_tokenize(train_data[0])),print(c)
   # d=[porter.stem(w.lower()) for w  in c]
   # print(' '.join(d))

# Using Logistic Regression from inbuild Skearn 

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
k_m=LogisticRegression(multi_class='auto',solver='lbfgs',max_iter=150)

In [32]:
y_train=np.array(y_train)
y_train=y_train.ravel()

y_test=np.array(y_test)
y_test=y_test.ravel()
y_train.shape,y_test.shape,X_train.shape,X_test.shape

((8235,), (2745,), (8235, 1500), (2745, 1500))

In [33]:
k_m.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=150, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [34]:
y_predicted=k_m.predict(X_test)

In [35]:
print(classification_report(y_predicted, y_test))

              precision    recall  f1-score   support

           0       0.95      0.80      0.87      1958
           1       0.49      0.70      0.57       437
           2       0.61      0.82      0.70       350

   micro avg       0.79      0.79      0.79      2745
   macro avg       0.68      0.77      0.71      2745
weighted avg       0.83      0.79      0.80      2745



In [36]:
y_predicted.shape

(2745,)

In [37]:
k_m.score(X_test,y_test)

0.785063752276867

# Using Multinomial Naive Bayes from inbulid Skearn 

In [38]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB()
mb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [39]:
y_pred2=mb.predict(X_test)

In [40]:
print(classification_report(y_pred2, y_test))

              precision    recall  f1-score   support

           0       0.98      0.72      0.83      2237
           1       0.29      0.77      0.42       234
           2       0.50      0.86      0.63       274

   micro avg       0.74      0.74      0.74      2745
   macro avg       0.59      0.78      0.63      2745
weighted avg       0.87      0.74      0.78      2745



In [41]:
mb.score(X_test, y_test)

0.740983606557377

# Using K-nearest Neighbors Classifier from inbulid Skearn 

In [42]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [43]:
y_pred4=neigh.predict(X_test)

In [44]:
print(classification_report(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.77      0.82      0.79      1652
           1       0.48      0.49      0.49       625
           2       0.68      0.51      0.58       468

   micro avg       0.69      0.69      0.69      2745
   macro avg       0.64      0.61      0.62      2745
weighted avg       0.69      0.69      0.69      2745

[[1351  236   65]
 [ 267  309   49]
 [ 130   99  239]]


In [45]:
neigh.score(X_test,y_test)

0.6918032786885245